### ISSUE TITLE
Dense Features config for DocumentClassificationTask returns MissingValueError

### ISSUE THREAD

**Issue by aptperson** [facebookresearch/pytext#1049]
I'm trying to uses dense features with text for a classification task, using the latest config versions and I’m using:
torch==1.2.0
torchtext==0.4.0
pytext-nlp==0.2.2
Python 3.7.4

And I keep getting the following error:
  File "/opt/conda/envs/py37/lib/python3.7/site-packages/pytext/config/serialize.py", line 193, in config_from_json
    f"missing value for {field} in class {cls_name} with json {json_obj}"
pytext.config.serialize.MissingValueError: missing value for column in class FloatListTensorizer.Config with json {'FloatListTensorizer': {'column': 'dense_feat', 'dim': 48, 'error_check': False, 'normalize': False}} 

Which I've traced to:
https://github.com/facebookresearch/pytext/blob/master/pytext/config/serialize.py#L187

It seems as though serialze.py is trying to tell me that I've specified the inputs incorrectly, which I don't understand as looking at:
https://github.com/facebookresearch/pytext/blob/master/pytext/data/tensorizers.py#L793
I have the 4 inputs.

## Steps to reproduce

  1. Generate the default config using:
pytext gen-default-config DocumentClassificationTask BiLSTMDocAttention > my_config.json

  2. Edit the config with the following:
            "dense": {
              "FloatListTensorizer": {
                "column": "dense_feat",
                "dim": 48,
                "error_check": false,
                "normalize": false
                }
  3. Train pytext using the above config results in:
pytext.config.serialize.MissingValueError: missing value for column in class FloatListTensorizer.Config with json {'FloatListTensorizer': {'column': 'dense_feat', 'dim': 48, 'error_check': False, 'normalize': False}} 

## Observed Results

  * What happened?  This could be a description, log output, etc.
the model didn't train

## Expected Results

  * What did you expect to happen?
The model to train

I'm assuming that I've miss understood how to specify the config for the task. Any help would be appreciated

**Comment by mwu1993** [comment]
Turns out since the "dense" field can only be "FloatListTensorizer", you don't need to include it. So

"dense": {
"column": "dense_feat",
"dim": 48,
"error_check": false,
"normalize": false
}

should work.
