### ISSUE TITLE
Seq2Label Example

### ISSUE THREAD

**Issue by braindead** [facebookresearch/pytext#111]
Is there documentation/example on how to use pytext for seq2label tasks?

**Comment by bethebunny** [comment]
You can see the config for seq2label models here:

https://pytext-pytext.readthedocs-hosted.com/en/latest/configs/pytext.task.tasks.SeqNNTask.Config.html

We'll add a demo for this eventually.

**Comment by snisarg** [comment]
@braindead does this look good? Do reopen this if you have more follow-ups.
