### ISSUE TITLE
 pytext export < config.json  

### ISSUE THREAD

**Issue by kevinew** [facebookresearch/pytext#112]
no such file: config.json

are you sure the model output is config.json?

**Comment by seayoung1112** [comment]
config.json is the config you used for training, not the trained model file

**Comment by kevinew** [comment]
In readme,   suggest show the export example as:

 (venv) $ pytext export  < demo/configs/docnn.json

**Comment by DomHudson** [comment]
My understanding is that you train from a configuration file, this will then save the output in a temporary location. Then, any further commands (such as `export`) using the same configuration file reference that temporary location somehow.

**Comment by snisarg** [comment]
If you don't specify the '--model' option, it'll pick up the model location from config's save_snapshot_path; which defaults to '/tmp/model.pt'. Look at https://github.com/facebookresearch/pytext/blob/b79a93b510ca0ace5e73f4cad399a11c902594a9/pytext/config/pytext_config.py#L73
The idea of the config is to have 1 file which specifies all these details, including where the model file was created and use that for exporting in this case.

**Comment by wby2016** [comment]
Does the file 'config.json' exist in the project from the beginning or is it generated later?I had the same problem 'no such file: config.json', Did the ‘readme’  miss any steps, or could you detail the process?thank you!

**Comment by snisarg** [comment]
Closing this. If you have more questions, reopen this issue.
