### ISSUE TITLE
"Multitask training with disjoint datasets" tutorial does now include disjoint datasets

### ISSUE THREAD

**Issue by maxdel** [facebookresearch/pytext#114]
If I understood it correctly, the tutorial shows multitask learning, but not disjoint datasets.

**Comment by borguz** [comment]
The tutorial explains how to do multitasking, where each task has its own (read disjoint) dataset.  This is in contrast to the case where there is a single dataset with each input text having multiple labels, one for each task.  Does this clear up the confusion?  If so I can add an explanation to the tutorial.  Thanks!

**Comment by maxdel** [comment]
The tutorial text itself does not include code that uses wikitext data, but by looking more closely into the [config file](https://github.com/facebookresearch/pytext/blob/0d1872312d4fd670ce3e388dd08c7deb85bbec8d/demo/configs/multitask_sst_lm.json#L54) everything becomes clear, thanks.
