### ISSUE TITLE
<repository>

### ISSUE THREAD

**Issue by Youlike708** [facebookresearch/pytext#116]
## Steps to reproduce

  1. _____
  2. _____
  3. _____

## Observed Results

  * What happened?  This could be a description, log output, etc.
## Expected Results

  * What did you expect to happen?

## Relevant Code

```
// TODO(you): code here to reproduce the problem
```

**Comment by geof90** [comment]
@Youlike708 Can you please fill in the issue template, otherwise I will close it as it is not actionable by us.

**Comment by m3rlin45** [comment]
I'm closing this, please open a new issue if you have a question.
