### ISSUE TITLE
Question regarding the output of the Hierarchical Intent and Slot Filling tutorial

### ISSUE THREAD

**Issue by xtagon** [facebookresearch/pytext#117]
Hi,

I'm following the tutorial here: https://pytext-pytext.readthedocs-hosted.com/en/latest/hierarchical_intent_slot_tutorial.html

I was able to run the REPL and replicate the result from the last section of the tutorial, which takes this as input:

```
{"text": "order coffee from starbucks"}
```

and returns something like this as output:

```
[{'prediction': [7, 0, 5, 0, 1, 0, 3, 0, 1, 1],
'score': [
        0.44425372408062447,
        0.8018286800064633,
        0.6880680051949267,
        0.9891564979506277,
        0.9999506231665385,
        0.9992705616574005,
        0.34512090135492923,
        0.9999979545618913,
        0.9999998668826438,
        0.9999998686418744]}]
```

My question is, how is this data structure encoded, and how do I use it to parse "order coffee from starbucks" into the hierarchical tree structure (intents and slots)?

**Comment by hikushalhere** [comment]
The `prediction` values are indices of the predicted actions. Given the actions vocabulary the ids should be converted to actual actions and given the action the tree structure is derived naturally. We will add the translation from id to string to make the predicted actions readable. Will that help?

**Comment by xtagon** [comment]
@hikushalhere Yes that helps, thank you so much for the quick reply 👍

**Comment by snisarg** [comment]
Closing issue as it seems resolved. Reopen for more questions. :)

**Comment by Vivicai1005** [comment]
> The `prediction` values are indices of the predicted actions. Given the actions vocabulary the ids should be converted to actual actions and given the action the tree structure is derived naturally. We will add the translation from id to string to make the predicted actions readable. Will that help?

Hi~ Have you added this translation function?
