### ISSUE TITLE
BERT pretraining input format

### ISSUE THREAD

**Issue by shreydesai** [facebookresearch/pytext#1177]
I'm wondering what the input format is for pretraining BERT/RoBERTa. If I have a large corpus (let's say Wikipedia and BooksCorpus put together), is each chunk of seq len 512 delimited by a `[SEP]` token? Is the `[CLS]` token used anywhere?

For example, if I had the following sentences and enforced a seq len of 5, would I end up with batches that look like this? For simplicity, I'm using regular tokens but I presume we will be tokenizing the inputs with wordpieces/BPE.

```
I like to go the movies.
Last night, I went to go see Nightcrawler.
It was a really fun experience.

->

I like to go to
movies [SEP] . Last night
, I went to go
see Nightcrawler . [SEP] It
was a really fun experience
. [SEP]
```

And, once we have the batch, we perform masking, etc.

**Comment by mwu1993** [comment]
Roughly speaking, yes that's right. Your data should be raw text and the data tensorizer should create something like you showed.

More specifically, follow the code in https://github.com/facebookresearch/pytext/blob/master/pytext/data/bert_tensorizer.py#L136 to see how the data is tensorized. The exact output format depends on the config values and the subclass of BERTTensorizerBase you're using. (You can drop a pdb into that method to inspect).

finally, the data is split into chunks of fixed length in https://github.com/facebookresearch/pytext/blob/master/pytext/data/packed_lm_data.py#L150, and you can also use pdb there to see the final data chunks.
