### ISSUE TITLE
Printing F1Micro/F1Macro during Evaluation.

### ISSUE THREAD

**Issue by DecentMakeover** [facebookresearch/pytext#1185]
I want to print F1 Micro and F1 macro metrics during evaluation.How could i do that?Any suggestion would be helpful.Thanks.

**Comment by mwu1993** [comment]
If you mean printing during validation (every epoch of training), then https://github.com/facebookresearch/pytext/blob/master/pytext/metrics/__init__.py#L232 is where the prints are happening. The `print` method for the `macro_prf1_metrics` attribute is already implemented in https://github.com/facebookresearch/pytext/blob/master/pytext/metrics/__init__.py#L178, so you could probably just call that.
