### ISSUE TITLE
F1 is a harmonic mean, not geometric 

### ISSUE THREAD

**Issue by int8** [facebookresearch/pytext#120]
Hi,
I think there might be a tiny mistake in documentation: 

https://github.com/facebookresearch/pytext/blob/master/pytext/docs/source/train_your_first_model.rst 

F1 score is described as geometric mean but I think it is in fact harmonic.

**Comment by bethebunny** [comment]
Yeah that's correct, will update :)

**Comment by snisarg** [comment]
Updating with https://github.com/facebookresearch/pytext/pull/127
