### ISSUE TITLE
How to specify batch_size and num_worker

### ISSUE THREAD

**Issue by jiangxiluning** [facebookresearch/pytext#1216]
Hi, pytext's documents are really poor. Can anybody tell me how can I specify the batch_size of training, val and testing, and How to specify the num_workers for dataloader?

**Comment by mwu1993** [comment]
batch sizes are in `data.batcher.{train,eval,test}_batch_size`. What do you mean by num_workers?

**Comment by jiangxiluning** [comment]
@mwu1993 num_workers is to specify dataloader worker processes

**Comment by mwu1993** [comment]
I don't think we have such a parameter (at least in the new design), as we don't use the pytorch dataloader. `distributed_world_size` specifies the number of workers for both training and loading data.
