### ISSUE TITLE
Dropout ignored in BiLSTMSlotAttention

### ISSUE THREAD

**Issue by fsonntag** [facebookresearch/pytext#123]
## Steps to reproduce
In `bilstm_slot_attn.py#93-96` the computed dropout representation is not re-used.

## Observed Results
No results observed, but might have performance impact.

## Expected Results
Dropout value is being used.

## Relevant Code

```
        rep = self.dropout(embedded_tokens)

        # LSTM representation
        rep, _ = self.lstm(embedded_tokens, seq_lengths, states)
        #Should be
        rep, _ = self.lstm(rep, seq_lengths, states)
```

A related question:
Is the used `SlotAttention` described somewhere? From looking at the code, it seems like a regular attention mechanism, but maybe I'm missing something. The readme states that the sequence tagger is based on `Lample et al. (2016)`, but the word tagger using this slot attention would be a different architecture then.

**Comment by snisarg** [comment]
This has been checked in, thank you so much for pointing out.

**Comment by fsonntag** [comment]
Thanks @snisarg !
Can you maybe also give me a small hint about the question I asked in the last paragraph?

**Comment by bethebunny** [comment]
SlotAttention doesn't have great documentation, and should probably be split out into a few classes. The best way to understand it for now is to read the code: https://github.com/facebookresearch/pytext/blob/master/pytext/models/representations/slot_attention.py

Essentially there are 3 supported attention modes, Dot, Multiply and Add (called CONCAT in the code).
The core line in building the attention states is https://github.com/facebookresearch/pytext/blob/master/pytext/models/representations/slot_attention.py#L42

All of the attention types construct a weight map, weight the attention state by the weight map, and concatenate it onto the original state.
- For Dot Attention, we simply dot the two states together
- For Multiply, we add in a single linear layer to Dot attention
- For Add, we concatenate the states together and then execute a 2 layer tanh MLP

**Comment by fsonntag** [comment]
Alright, thanks a for the explanation!
So do I understand it then correctly that the Dot mode is not really an attention in the sense that we weigh different parts of the input? Because it does not have any trainable weights, but the output is just a transformation of the input

**Comment by hikushalhere** [comment]
@fsonntag You're right that the DOT mode is only a transformation.

I am closing this issue since there isn't any actionable item here.
