### ISSUE TITLE
Can pytext support Chinese? If support, what should i do to train Intent-Slot model on Chinese Dataset.

### ISSUE THREAD

**Issue by wuyunxiangwyx** [facebookresearch/pytext#130]

**Comment by snisarg** [comment]
Currently, we have a very simple Featurizer which can work for English and similar languages only. We'll look into adding one for Chinese soon, but don't have immediate plans for it. We'll appreciate if you can send us a pull request though! 

See a more detailed answer from @m3rlin45 here: https://www.facebook.com/groups/pytext/permalink/929836947224147/
