### ISSUE TITLE
find_config_class only looks for pytest Tasks

### ISSUE THREAD

**Issue by michaelcapizzi** [facebookresearch/pytext#145]
## Steps to reproduce

  1. build custom `<Task>`
  2. `pytext gen-dfeault-config [CustomTask]`
 
## Observed Results

```
Exception: Unknown task class: [CustomTask]
```

  * What happened?  This could be a description, log output, etc.

I believe it's because  `utils.documentation_helper.find_config_class()` will only look at `pytext` modules (https://github.com/facebookresearch/pytext/blob/d998f753bf05131a375a0ba8f8c0f4626a8d6c48/pytext/utils/documentation_helper.py#L145)

## Expected Results

  * What did you expect to happen?

I was hoping to be able to generate a default `config` for my new `Task` just as I could if it were a "predefined" `Task`.

**Comment by elans2** [comment]
I have the same problem, can't generate config file using user task

**Comment by snisarg** [comment]
@elans2 what error do you see when you comment that part of the code? 
@Titousensei any reason to only allow pytext Tasks only?

**Comment by michaelcapizzi** [comment]
Update:

I was able to get it to work with a slight modification to `pytext.utils.documentation_helper.find_config_class()` (comments include the errors that I encountered):

```
def find_config_class(class_name):
    """
        Return the set of PyText classes matching that name.
        Handles fully-qualified `class_name` including module.
    """
    module_part = None
    if "." in class_name:
        m = class_name.split(".")
        class_name = m[-1]
        module_part = ".".join(m[:-1])

    ret = set()
    for mod_name, mod in list(modules.items()):            # avoids this error: RuntimeError: dictionary changed size during iteration
        # if not mod_name.startswith("pytext"):                # removed to allow looking for custom Tasks
        #     continue
        try:                                                                        # avoids this error: ModuleNotFoundError: No module named '_gdbm'
            getmembers(mod, isclass)
        except:
            continue
        for name, obj in getmembers(mod, isclass):
            if name == class_name:
                if not module_part or obj.__module__ == module_part:
                    ret.add(obj)
    return ret
```

As @elans2 noted, however, this only required *after* I imported the custom `Task`.  I'm not knowledgeable enough to know how to import those custom `Task`s before running `pytext gen-default-config` from the command line however.

**Comment by Titousensei** [comment]
Thanks for reporting the issue and providing a fix. Yes, there's 2 issues here:
1) we only look at the module "pytext". That's a mistaked.
2) the new tasks are not registered in pytext main.
I'll submit a fix soon.

**Comment by hikushalhere** [comment]
Closing the issue since the PR (#196 ) has been merged to master.
