### ISSUE TITLE
Example usage for pretrained_embeddings_path?

### ISSUE THREAD

**Issue by nlathia** [facebookresearch/pytext#158]
Is there any documentation or examples for using pretrained embeddings?

Specifically, I've found that the config can take a `pretrained_embeddings_path`, which I assume is a path to a file containing embeddings- how is that file structured?

https://pytext-pytext.readthedocs-hosted.com/en/latest/configs/pytext.models.embeddings.word_embedding.WordEmbedding.Config.html

**Comment by bethebunny** [comment]
The ATIS tutorial has an example of using the Stanford GloVe embeddings:
https://pytext-pytext.readthedocs-hosted.com/en/latest/atis_tutorial.html#download-pre-trained-word-embeddings
https://nlp.stanford.edu/projects/glove/

The format for these files is space-separated lines, where the first column is the word, and the remaining columns are ascii-encoded float values. For instance, for a 5-dimension embedding,

```
the -0.038194 -0.24487 0.72812 -0.39961 0.083172
of -0.1529 -0.24279 0.89837 0.16996 0.53516
to -0.1897 0.050024 0.19084 -0.049184 -0.089737
```
