### ISSUE TITLE
difference between word_feat and seq_word_feat

### ISSUE THREAD

**Issue by michaelcapizzi** [facebookresearch/pytext#178]
Forgive me that this isn't quite an issue.  If there is a more appropriate forum for these kinds of questions, please let me know, and I'll close this.

But I'm wondering what the difference is between `word_feat` and `seq_word_feat` here: https://github.com/facebookresearch/pytext/blob/faccba193e28ce1b7e532052a14f55101b71a2e5/pytext/config/field_config.py#L60

Any insight would be greatly appreciated.

**Comment by seayoung1112** [comment]
seq_word_feat is only used for seq models right now (SeqNN and ContextualIntentSlot), the FeatureConfig class is a set of all possible features for all models right now, we'll break it down to let each model having it's own feature definition in future.

**Comment by michaelcapizzi** [comment]
Thanks @seayoung1112 for the quick response.  Closing.
