### ISSUE TITLE
export_caffe2_path for each task in DisjointMultitask mode

### ISSUE THREAD

**Issue by puttkraidej** [facebookresearch/pytext#192]
I followed multitask demo,
$ pytext train < multitask_sst_lm.json

My issue is how do I export as caffe2 (.c2) for each tasks. I wanna train my own multitask and expect multiple binary-classifiers in return. The question is what should I do to export_caffe2_path if I needed outputs for each tasks??

**Comment by jayrodge** [comment]
I'm adding following line in the config.json:
`"save_snapshot_path": "./model.pt",
    "export_caffe2_path": "./model.c2"`

But the model is not being saved, any idea?

**Comment by puttkraidej** [comment]
The .pt one will be save but not for .c2, anyway how can we use the model by tasks then?

**Comment by borguz** [comment]
Currently caffe2 export for multitask is not implemented.  I'll take this up this week.
For now, it's possible to save individual modules and load them into a single-task pytext run to export the model as workaround.

**Comment by puttkraidej** [comment]
Thanks both of you @jayrodge @borguz, by the way how to save individual modules? I because I tried put save_snapshot_path under tasks{...} but, unfortunately it would work that way. I think I might did something wrong.

**Comment by borguz** [comment]
You can set modules_save_dir in the PyText config, then can set save_path for each module you want to save.  save_path is relative to modules_save_dir.

**Comment by puttkraidej** [comment]
@borguz  thanks once again for this suggested work around.

Anyway, even if I employed single-task mode (i,e,. DocClassificationTask), caffe2 export function still unworkable (only .pt came out as output). Then I decided to rely on,
`$pytext export --output-path <my_caffe2> < <my_single_task_config>`
and it works :)

**Comment by borguz** [comment]
Should now be handled by https://github.com/facebookresearch/pytext/pull/197.
Add an export config to any sub-task to export the model.
