### ISSUE TITLE
can't store tensors in the "context"

### ISSUE THREAD

**Issue by silky** [facebookresearch/pytext#200]
in say `trainer.py`, just after the model is run, put something like this:

```
logits = model(*inputs)
...
context["loss"] = logits
```

this gives an error:

```
  File "/home/noon/tools/miniconda3/envs/pytext/lib/python3.7/site-packages/torch/tensor.py", line 18, in __deepcopy__
    raise RuntimeError("Only Tensors created explicitly by the user "
RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment
```

coming from the use of deep_copy in the `./pytext/data/data_handler.py` here:

```
            # Due to a limitation in PyTorch's distributed training backend that
            # enforces that all the parallel workers to have the same number of
            # batches we keep yielding the last batch until the requested total
            # number of batches is fullfilled
            if i == num_batches - 1:
                context = deepcopy(context)
                context.update({BatchContext.IGNORE_LOSS: True})
                for _j in range(num_batches, self.total_num_batches):
                    yield (input, target, context)
```

i'm trying to use the context to pass around some tensors that i want to use as part of other calculations/visualisations; but it doesn't seem supported.

am i missing some better way to do this?

**Comment by hikushalhere** [comment]
@silky I was able to repro the exception locally. Yes, `context` is the way to pass batch level data for downstream usage (e.g., metric calculation). However, given the limitation that only Tensors created explicitly by the user can be used with deepcopy, one way to do this is to clone the Tensor.
`context["logits"] = [l.clone().detach() for l in logits]`

**Comment by silky** [comment]
@hikushalhere cool okay; that's pretty much what i did

i had also tried to use the context to pass a tensor that i needed to be included in the gradients (when computing the penalty for the attention in the self-attention paper); in that case this approach would fail, right?

**Comment by hikushalhere** [comment]
@silky Are you referring to the orthogonality constraint that's enforced by the penalty on attention matrix? If so, the penalty tensor should be user created and it shouldn't be a problem with deepcopy.

**Comment by silky** [comment]
@hikushalhere what i meant was that _if_ i'm using the attention matrix in that calculation, i can't pass it in via the clone-detach, it can't be done via the context dict, it has to be done more directly.
