### ISSUE TITLE
Running out of memory when training a text classifier

### ISSUE THREAD

**Issue by dsalfran** [facebookresearch/pytext#202]
PyText crashed running a text classification task with a large dataset.

## Steps to reproduce

  1. Build custom dataset with 450k examples where the texts have 350 words on average
  2. pytext train < config.json
where config.json is:
```
{
    "task": {
        "DocClassificationTask": {
            "data_handler": {
                "train_path": "datasets/train_pytext.tsv",
                "eval_path": "datasets/test_pytext.tsv",
                "test_path": "datasets/test_pytext.tsv"
            }
        },
        "distributed_world_size": 24
    }
}
```

## Observed Results
  
  System crash due to lack of memory. The process was running in a system with 64 CPUs and 256 GB of memory.

## Expected Results

 I have trained models before using pytext and smaller datasets with successful results. It was surprising to see it crash.

**Comment by hikushalhere** [comment]
@dsalfran Thanks for reporting the issue. Can you give an estimate of how big your dataset is (in GB) and if you expect it to fit in memory given your machine configuration?

**Comment by habout632** [comment]
happens to me 
dataset is 0.036GB=36MB
machine configuration is 32G(10G used) 　pytext will cost rest 22G when started

**Comment by habout632** [comment]
memory leaks heavily

**Comment by m3rlin45** [comment]
I worked with @habout632 on this in the support group, he had set up his data file columns as: [text, class], the default setting for "columns_to_read" is [class, text, dict_feat]. Once they set columns_to_read correctly, the problem went away. @dsalfran, can you confirm you don't have the same issue?

**Comment by dsalfran** [comment]
Thanks @m3rlin45, I added the correct value of "columns_to_read" to the configuration file and the problem went away!
