### ISSUE TITLE
The format of the training set for Sequence taggers task

### ISSUE THREAD

**Issue by yanqiangmiffy** [facebookresearch/pytext#209]
## Steps to reproduce

I want to ask what is the format of the training set if I want to do the word tagging task? Use the default JointModelDataHandler，Can give an example?

## Expected Results
Take a snapshot of the specific annotation method or content of the training set?

**Comment by chenyangyu1988** [comment]
@yanqiangmiffy check out joint_data_handler_test.py, there is sample data for test, will it help?

**Comment by yanqiangmiffy** [comment]
> @yanqiangmiffy check out joint_data_handler_test.py, there is sample data for test, will it help?

thanks
