### ISSUE TITLE
rnng model CUDA error: initialization error

### ISSUE THREAD

**Issue by Vivicai1005** [facebookresearch/pytext#238]
**Problems:**

I had set the "use_cuda_if_available" to be true in the rnng.json file and run pytext train < demo/configs/rnng.json. Then got "RuntimeError: CUDA error: initialization error" and "RuntimeError: Input and hidden tensors are not at the same device, found input tensor at cuda:0 and hidden tensor at cpu"

**ENV**
1. Python 3.6.5 :: Anaconda, Inc.
2.NVIDIA-SMI 390.30

Thanks so much!

**Comment by seayoung1112** [comment]
Hi @Vivicai1005, RNNG model is trained by Hogwild trainer which only runs on CPU now

**Comment by xtagon** [comment]
I'm also getting `AttributeError: 'NoneType' object has no attribute 'export_output_names'`

**Comment by wowitsmrinal** [comment]
Hey @Vivicai1005 

The RNNG model currently doesn't support ONNX export because of its dynamic graph. As an alternative, we plan to make PyTorch 1.0 JIT support available in time.
