### ISSUE TITLE
pytext export   (Context: Bad node spec)   anybody can help

### ISSUE THREAD

**Issue by lonngxiang** [facebookresearch/pytext#243]
## Steps to reproduce

  1. _____
  2. _____
  3. _____

## Observed Results

  * What happened?  This could be a description, log output, etc.
## Expected Results

  * What did you expect to happen?

## Relevant Code

```
// TODO(you): code here to reproduce the problem
```

**Comment by Titousensei** [comment]
No information in the description, that's bad. Likely duplicate of #240.
