### ISSUE TITLE
nothing happens when exporting ulmfit model to caffe

### ISSUE THREAD

**Issue by akanshajainn** [facebookresearch/pytext#283]
## Steps to reproduce

  1. pip install pytext-nlp
  2. pytext export --model ../models/model.h5 --output-path model.caffe 

Dependency : Pytorch 1, Python 3.6, pytext-nlp==0.1.2

## Observed Results
```
(pyone) user@system:~/akansha/pytext/pytext$ pytext export --model ../models/model.h5 --output-path model.caffe 
No config file specified, reading from stdin

```
## Expected Results

I was expecting that for given pytroch model (model.h5), it will save the caffe model (model.caffe). Instead it didn't give any error and was stuck giving no output. I had to kill the process.

## Relevant Code

```
// TODO(you): code here to reproduce the problem
```

**Comment by snisarg** [comment]
It's waiting for the model config (which is required, besides the pytorch model) from the stdin.

You can redirect your config like it's done in https://pytext-pytext.readthedocs-hosted.com/en/latest/execute_your_first_model.html#export-the-model.

**Comment by akanshajainn** [comment]
*You can also pass in a configuration **to infer some of these options.** In this case let’s do that because depending on how you’re following along your snapshot might be in different places!*

Instead of passing the model through config, I am passing it through options given. What's the difference?
Does it need more than the pytorch model and output model name ? If yes, then why isn't mentioned?

**Comment by snisarg** [comment]
I looked into the code. Looks like we are reading the config off of the model file, so don't really need it if the "--model" is specified. 

I'll file a task for this. We welcome your contribution too. :) In the meantime, just pass any config to unblock yourself.

**Comment by snisarg** [comment]
We'll track the code fix in the referenced issue.
Thanks for bringing this up.
