### ISSUE TITLE
Uprade to ONNX 1.4.1

### ISSUE THREAD

**Issue by WilliamTambellini** [facebookresearch/pytext#284]
## Steps to reproduce

  1. install pytext : see requirements.txt imposes onnx 1.3
  2. export a pytext model to onnx 
  3.  the onnx file is limited to onnx opset 8

## Observed Results
  * What happened?  onnx 1.3
## Expected Results
 onnx 1.4.1

https://github.com/onnx/onnx/releases/tag/v1.4.1

**Comment by Titousensei** [comment]
Latest version uses onnx 1.5.0
