### ISSUE TITLE
pytext vs bert

### ISSUE THREAD

**Issue by ArunkumarRamanan** [facebookresearch/pytext#291]
## Steps to reproduce

  1. _____
  2. _____
  3. _____

## Observed Results

  * What happened?  This could be a description, log output, etc.
## Expected Results

  * What did you expect to happen?

## Relevant Code

```
// TODO(you): code here to reproduce the problem
```

**Comment by geof90** [comment]
Is there a specific question you are asking? Can you fill in the description?

**Comment by Titousensei** [comment]
No info, closing.
