### ISSUE TITLE
Support for mixed-precision training

### ISSUE THREAD

**Issue by swaroopgrs** [facebookresearch/pytext#319]
I am not sure if there is a way to do it already? But, is there is any roadmap for mixed-precision support may be using Amp 1.0?

**Comment by swaroopgrs** [comment]
Just read the paper and there is a plan to add FP16 support. If you think mixed-precision is covered there you can close the issue.

**Comment by chenyangyu1988** [comment]
@swaroopgrs Yeah, we are working on mixed precision training using Apex.amp and Apex.fp16_utils.

**Comment by borguz** [comment]
This is supported.  Set use_fp16: true
