### ISSUE TITLE
How to add customized module in build-in tasks

### ISSUE THREAD

**Issue by stucou** [facebookresearch/pytext#452]
Hi all,
Do we have any method to add a new module to build in tasks?

For example, I'd like to add my own Representation module into DocClassificationTask,I find in DocModel.Config, the representation is defined as union of three predefined module, but I'd like to use my subclass of Representation. 

Thanks a head for any reply!

**Comment by i4never** [comment]
DocModel is deprecated now. 
What I find is :
![image](https://user-images.githubusercontent.com/10850020/57754792-dd2f4700-7721-11e9-8389-ff74c03a97fa.png)
Maybe ``create_fn`` is what u need if you want custom representation module.
From an old friend :)

**Comment by Titousensei** [comment]
You can use `--include` to your command line to import your own components. There's a full example in the tutorial "Creating A New Model".
