### ISSUE TITLE
Tutorial: PyText Models in your app does not work

### ISSUE THREAD

**Issue by AnakTeka** [facebookresearch/pytext#476]
## Steps to reproduce

  1. Folllowing tutorial from here https://pytext-pytext.readthedocs-hosted.com/en/latest/atis_tutorial.html
  2. Run flask server from this tutorial with newly trained model from step 1 https://pytext-pytext.readthedocs-hosted.com/en/latest/pytext_models_in_your_app.html

## Observed Results

  * The flask server did not output any values although the predictor able to predict entity for each of the words
```
>>> tokens
['i', 'want', 'to', 'fly', 'from', 'new', 'york', 'at', '838', 'am', 'and', 'arrive', 'in', 'denver']
>>> predicted_labels
array([ 1,  1,  1,  1,  1,  3,  3,  1, 24, 24,  1,  1,  1,  2])
```
  * 

## Expected Results

  * As shown in tutorial, the model should able to output the spans for cities name, something like `i want to fly from new york at 838 am and arrive in denver` and should be able to output `[[19, 27], [52, 58]]` for the cities spans
## Relevant Code

Looking through `atis.py` 

https://github.com/facebookresearch/pytext/blob/8b4fb7ebc5adfbad588fb6e1520b732bb1a088f4/demo/flask_server/atis.py#L65-L77

this is because it checks if label is `B-` tag, `labels` is created from labels dictionary and created from this part of code

https://github.com/facebookresearch/pytext/blob/8b4fb7ebc5adfbad588fb6e1520b732bb1a088f4/demo/flask_server/atis.py#L50-L59

Unfortunately, `labels` does not have any IOB tags as its values, which means this part line of code will never run.

https://github.com/facebookresearch/pytext/blob/8b4fb7ebc5adfbad588fb6e1520b732bb1a088f4/demo/flask_server/atis.py#L68-L72

Instead, if I change the code to simply append whether `city_name` in label
```
city_token_ranges = []                                   
for token_idx, label_idx in enumerate(predicted_labels): 
┆   label = labels[label_idx]                            
┆   if "city_name" in label:                             
        city_token_ranges.append(token_ranges[token_idx])
    return city_token_ranges
``` 

It is able to output span for the cities names, but it lost its IOB tags, when new york should be tagged as a one city.
```
>>> city_token_ranges
[[19, 22], [23, 27], [52, 58]]
>>> s = 'i want to fly from new york at 838 am and arrive in denver'
>>> for span in city_token_ranges:
           print(s[slice(*span)])
new
york
denver
```
@wowitsmrinal

**Comment by mwu1993** [comment]
I'm not very familiar with this model and label names, but maybe we can join consecutive spans automatically? Something like

```
city_token_ranges = []
for token_idx, label_idx in enumerate(predicted_labels):
    label = labels[label_idx]
    if "city_name" in label:
        current_start, current_end = token_ranges[token_idx]
        if city_token_ranges:
            prev_start, prev_end = city_token_ranges[-1]
            if current_start == prev_end + 1:
                city_token_ranges[-1] = prev_start, current_end
                continue
        city_token_ranges.append((current_start, current_end))
```

If this works for you, I can make a short PR.

**Comment by wowitsmrinal** [comment]
Fixed by https://github.com/facebookresearch/pytext/pull/570
Thanks for reporting!
