### ISSUE TITLE
While I employ LMTtask I got this error message >> File "....pytext/models/representations/bilstm.py", AttributeError: module 'torch.onnx' has no attribute 'is_in_onnx_export'

### ISSUE THREAD

**Issue by puttkraidej** [facebookresearch/pytext#489]
## Steps to reproduce

  1. My pytext install from git+https://github.com/facebookresearch/pytext.git@ab5a021c03dd96425103bcd9e2542670f462c623#egg=pytext_nlp
  2. torch.__version__ >> '1.0.1.post2'
  3. and here is my config file

{
	"config": {
		"task": {
			"LMTask": {
				"features": {
					"load_path": null,
					"save_path": null,
					"freeze": false,
					"shared_module_key": null,
					"word_feat": {
						"embed_dim": 300,
						"freeze": false,
						"embedding_init_strategy": "random",
						"embedding_init_range": null,
						"export_input_names": [
							"tokens_vals"
						],
						"pretrained_embeddings_path": "",
						"vocab_file": "",
						"vocab_size": 0,
						"vocab_from_train_data": true,
						"vocab_from_all_data": false,
						"vocab_from_pretrained_embeddings": false,
						"lowercase_tokens": true,
						"min_freq": 1,
						"mlp_layer_dims": []
					},
					"seq_word_feat": null,
					"dict_feat": null,
					"char_feat": null,
					"pretrained_model_embedding": null
				},
				"featurizer": {
					"SimpleFeaturizer": {
						"sentence_markers": null,
						"lowercase_tokens": true,
						"split_regex": "\\s+",
						"convert_to_bytes": false
					}
				},
				"data_handler": {
					"LanguageModelDataHandler": {
						"columns_to_read": [
							"text"
						],
						"shuffle": true,
						"sort_within_batch": true,
						"train_path": "train.txt",
						"eval_path": "valid.txt",
						"test_path": "test.txt",
						"train_batch_size": 128,
						"eval_batch_size": 128,
						"test_batch_size": 128,
						"append_bos": true,
						"append_eos": true
					}
				},
				"trainer": {
					"random_seed": 0,
					"epochs": 10,
					"early_stop_after": 0,
					"max_clip_norm": null,
					"report_train_metrics": true
				},
				"optimizer": {
					"type": "adam",
					"lr": 0.001,
					"weight_decay": 1e-05,
					"momentum": 0.0
				},
				"scheduler": {
					"type": "none",
					"step_size": 30,
					"gamma": 0.1,
					"T_max": 1000,
					"eta_min": 0,
					"patience": 5,
					"threshold": 0.0001,
					"threshold_is_absolute": false,
					"cooldown": 0,
					"cut_frac": 0.1,
					"ratio": 32,
					"non_pretrained_param_groups": 2,
					"lm_lr_multiplier": 1.0,
					"lm_use_per_layer_lr": false,
					"lm_gradual_unfreezing": true
				},
				"exporter": null,
				"model": {
					"representation": {
						"load_path": null,
						"save_path": null,
						"freeze": false,
						"shared_module_key": null,
						"dropout": 0.4,
						"lstm_dim": 1550,
						"num_layers": 4,
						"bidirectional": true
					},
					"decoder": {
						"load_path": null,
						"save_path": null,
						"freeze": false,
						"shared_module_key": null,
						"hidden_dims": []
					},
					"output_layer": {
						"load_path": null,
						"save_path": null,
						"freeze": false,
						"shared_module_key": null,
						"loss": {}
					},
					"tied_weights": true,
					"stateful": false
				},
				"labels": null,
				"metric_reporter": {
					"output_path": "/tmp/test_out.txt"
				}
			}
		},
		"use_cuda_if_available": true,
		"distributed_world_size": 4,
		"export_caffe2_path": "xxx.c2",
		"save_snapshot_path": "xxx.pt"
	}
}

## Observed Results

  * Data already loaded to gpu and seem like it is going to train but, it always fails with this error

**Comment by experiencor** [comment]
how did you solve this

**Comment by puttkraidej** [comment]
set 
"exporter": {}
and 
"labels": {}

@experiencor
