### ISSUE TITLE
Bert Support ?

### ISSUE THREAD

**Issue by Sanjeev2487** [facebookresearch/pytext#498]
Hi,
Is there any plan to add support for BERT under pytext ?
If not can anyone explain the steps to use BERT here for text classification and slot extraction ?

**Comment by bethebunny** [comment]
We're working on a similar model called BiTransformer which is not ready to be open sourced, but we have tentative plans to.

We don't have active plans on integrating HuggingFace, but would welcome contributions to add it, as I think that would be particularly valuable to PyText users.

To use these models, you generally need to replace the Embedding component in a DocClassification or WordTagging task with the "embedder" or "decoder" (depending on the project nomenclature, whatever component contains the transformer network), and then train the task as normal.

**Comment by borguz** [comment]
BERT models are now supported for document classification, although export support is still coming.  Look for bert_classification_models.py
