### ISSUE TITLE
Where is the /tmp folder 

### ISSUE THREAD

**Issue by mahanswaray** [facebookresearch/pytext#719]
## Steps to reproduce
I tried the basic demo docnn.json config, i successfully trained and tested my model
it says the model is stored in tmp/ folder. so are the test results
but where is this /tmp folder. 
i can't find it anywhere, i have used a virtual env.
  1. _____
  2. _____
  3. _____

## Observed Results

 Should the tmp folder create on it own but it's not?
## Expected Results

  * What did you expect to happen?

## Relevant Code

```
// TODO(you): all i did was create two train and test files and placed them in 
pytext_venv/lib/python3.6/site-packages/pytext/data/vertical_train_data.tsv
same location for test
then used the mock docnn config json, changed the file name and placed it in my current working directory 
and then pytext train < docnn.json
```

**Comment by Titousensei** [comment]
I'm guessing you're on Windows. Can you look in `C:\temp\` to see if the files are here?

**Comment by mahanswaray** [comment]
No I'm using a mac

**Comment by Titousensei** [comment]
On a mac the directory /tmp should exist (virtual env or not should not make a difference). You can try the following command in a terminal: `ls /tmp/`. If you exported your model you should see a file file `/tmp/model.caffe2.predictor`. The test results should be in `/tmp/test_out.txt`.
