### ISSUE TITLE
Questions on the implementation of AUCPR loss

### ISSUE THREAD

**Issue by Jongchan** [facebookresearch/pytext#755]
First of all, thank you for sharing the implementation. It helps a lot since I want to try out this loss term.

https://github.com/facebookresearch/pytext/blob/0a77e34e555750311ede54514c3c85b133b258f3/pytext/loss/loss.py#L242

The implementation seems to follow the loss form in eq12 in the paper (multiplied by 1-alpha).

My questions are as follows:
(1) why not use the exact form of equation 12? why multiply by 1-alpha_t?
(2) shouldn't it be `(1.0 + lambdas) * (1.0 - self.precision_values)` rather than `1.0 + lambdas * (1.0 - self.precision_values)`?

**Comment by Jongchan** [comment]
Just found out that the term is meaning less. closing the issue.

**Comment by erikyao** [comment]
Hi @Jongchan! I also come to question (2). Could you please explain why it's meaningless?

**Comment by supriyaarun27** [comment]
Hi, I have the same questions both 1 & 2. Could you explain why you it's meaningless?
