### ISSUE TITLE
New API plan

### ISSUE THREAD

**Issue by deepali-c** [facebookresearch/pytext#759]
I am curious to know if we have any information on timeline w.r.t completion of implementation of  the New API. 
Will there be a `v0.2.1` soon?

**Comment by Titousensei** [comment]
The new API implementation is complete as of 0.2.0. Is there anything you think is missing?
The next v0.2.1 will be a bug fix without breaking changes (hopefully).

**Comment by deepali-c** [comment]
Thanks @Titousensei, for your response. I had observed some issues and had read in the FB group that more changes are needed in the Predict API. 

By when can we expect `v0.2.1` with the fixes.

**Comment by Titousensei** [comment]
We're looking at the list of known issues prioritizing them for the next releases. v0.2.1 should be released in early August at the latest.

**Comment by deepali-c** [comment]
Thanks @Titousensei, this helps.
