### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/model.pt'

### ISSUE THREAD

**Issue by roschuhsnr** [facebookresearch/pytext#784]
Hi, I am having issues while completing the pytext "Train your first modell" demo (https://pytext.readthedocs.io/en/master/train_your_first_model.html).

When training the demo/configs/docnn.json file i have troubles with following error: 
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/model.pt'
Anybody knows this issue? Thanks a lot for future answers.

Edit: 
I am using Windows 10 and the error occurs while trying so save the model, AFTER the 10 evaluating epochs.

**Comment by chenyangyu1988** [comment]
You just need to change a path in windows. /tmp is for Linux
