### ISSUE TITLE
How to pass/override config parameters via command-line options?

### ISSUE THREAD

**Issue by ishalyminov** [facebookresearch/pytext#842]
## Steps to reproduce

  1. `pytext gen-default-config JointTextTask`

## Observed Results

ERROR - Cannot create this config because some fields don't have a default value: Failed to specify {'labels'} for <class 'pytext.task.tasks.JointTextTask.Config'>

  * What happened?  This could be a description, log output, etc.
## Expected Results

Config json created

  * What did you expect to happen?

 I'm following [this tutorial](https://medium.com/iambot/ai-assistance-with-pytext-6308d896566d) where `labels` are part of JSON config and look as follows:
```
"labels": [
  {
    "DocLabelConfig": {}
  },
  {
    "WordLabelConfig": {}
  }
]
```
For my needs though, I want to learn how to provide those via command-line arguments - at least the code suggests that it's possible..
Of course 'labels' is not the only thing that's needed by this config, but I only need to understand the overall idea.

**Comment by hikushalhere** [comment]
@Titousensei can you please help Igor with the correct way to supply config params?

**Comment by ishalyminov** [comment]
more context here: https://stackoverflow.com/questions/57245081/pytext-providing-config-parameters-via-command-line

**Comment by Titousensei** [comment]
This article you linked is using an older version of PyText, probably v0.1.0. The new version of PyText will try and load this older version of a config and try to convert it to the latest version, but his is not always possible to do automatically, and it seems to be the case here.

As you suggest, it's better to start fresh from a new config with the latest version. `JointTextTask` is not supported anymore and was renamed `JointTextTask_Deprecated`. The new version is called `IntentSlotTask`. You can get a config by running the command:

  `pytext gen-default-config IntentSlotTask > my_config.json`

You will need to edit the file `my_config.json` to fill in the `field_names` (previously called `columns_to_read`), `train_filename` (and other filenames, previously called `train_path`), `pretrained_embeddings_path`, and maybe others.

Look at `demo/configs/new_joint.json` for a minimal working example.

**Comment by ishalyminov** [comment]
@Titousensei thanks! So with the `IntentSlotTask` example working for me, here's my original question. Say, I want to generate this config but override some of the parameters right away via the `options` argument, e.g.:

```bash
pytext gen-default-config task.IntentSlotTask.data.Data.batcher.PoolingBatcher.eval_batch_size=1 IntentSlotTask
```

for which I get:
```bash
File "/home/t-igsha/miniconda3/envs/dstc8/lib/python3.7/site-packages/pytext/main.py", line 124, in gen_config_impl
    f"Unknown task class: {task_name} " "(try fully qualified class name?)"
Exception: Unknown task class: task.IntentSlotTask.data.Data.batcher.PoolingBatcher.eval_batch_size=1 (try fully qualified class name?)
```
(The above example might look weird but I have my specific use-case in which it makes more sense.)
What is the correct way to provide such an option?

**Comment by Titousensei** [comment]
@ishalyminov, this is not currently possible, but it's coming soon with pull request #856 where you will be able to do:

  `pytext gen-default-config IntentSlotTask eval_batch_size=1`

In the mean time, you need to manually edit your config to set `"eval_batch_size": 1` in the json file.

**Comment by ishalyminov** [comment]
Got it, thanks!
