### ISSUE TITLE
Guide and documentation link is not exist.

### ISSUE THREAD

**Issue by GitHub30** [facebookresearch/pytext#91]
The following links is broken.

https://github.com/facebookresearch/pytext/blob/master/CLOUDS.md

https://pytext.readthedocs.io/installation.html

**Comment by geof90** [comment]
Thanks! We have linked to the right section in our [clouds](https://pytext-pytext.readthedocs-hosted.com/en/latest/installation.html#cloud-vm-setup) and [installation](https://pytext-pytext.readthedocs-hosted.com/en/latest/installation.html) docs from our README.
