### ISSUE TITLE
RuntimeError: bool value of Tensor with more than one value is ambiguous

### ISSUE THREAD

**Issue by deepali-c** [facebookresearch/pytext#934]
## Steps to reproduce
Execute steps to test Custom Tensorizer - https://pytext.readthedocs.io/en/master/tensorizer.html 

## Observed Results
```
    assert words_tensors == tensor([[2, 3, 4, 5], [6, 7, 8, 1]])
RuntimeError: bool value of Tensor with more than one value is ambiguous
```

## Expected Results
The test should pass.

**Comment by deepali-c** [comment]
Updating code locally to correctly compare the tensors at the end helps here. 
The example in the document needs to be updated likewise:

 ``` 
assert torch.all(torch.eq(words_tensors, tensor([[2, 3, 4, 5], [6, 7, 8, 1]])))
assert torch.all(torch.eq(seq_len_tensors, tensor([4, 3])))
```

**Comment by deepali-c** [comment]
Thanks @hudeven :-) .

**Comment by deepali-c** [comment]
One more thing, there is an additional bracket at the following line - 
`words_tensors, seq_len_tensors = tensorizer.tensorize(numberized_rows))`

**Comment by mwu1993** [comment]
https://github.com/facebookresearch/pytext/pull/971
